### ISSUE TITLE
New Empty entries and package duplicates

### ISSUE THREAD

**Issue by SovnSkyrim** [Excinerus/AI-Overhaul-Patcher#2]
https://cdn.discordapp.com/attachments/715098946221113345/796073669025595412/unknown.png
https://cdn.discordapp.com/attachments/715098946221113345/796073695339610133/unknown.png
https://cdn.discordapp.com/attachments/715098946221113345/796073726332239883/unknown.png

It's almost always Master > USSEP > AIO > Third Mod > Patcher

Ran with latest synthesis

**Comment by Excinerus** [comment]
Packages aren't being duplicated, packages that were removed by USEEP/AIO an reinstated by later mods are removed, packages added by USEEP/AIO are forwarded.  what you're seeing is their alignment not corresponding to each of their original mods. At times combining package priorities from different mods requires judgement from the user/Modder, so they're just appended to the package list without a priority and thus appear at the end of it in xEdit, more work can be done on that issue.

Fixed the empty null entries, (element with null FormID instead of a null element) when merging outfits and default packages. [a6d5b77]
